version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      # Credentials
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
      # (Optional) set a subdirectory for the database files
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # Persist data on the host
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped